[package]
name = "pioc"
version = "0.1.0"
edition = "2021"

[dependencies]
pioc-asm = { path = "../pioc-asm", optional = true }
pioc-core = { path = "../pioc-core" }
pioc-macros = { path = "../pioc-macros", optional = true }

[features]
default = ["macros"]
macros = ["dep:pioc-macros"]
std = ["dep:pioc-asm", "pioc-core/std"]
alloc = ["pioc-core/alloc"]
